### ISSUE TITLE
Important thing

### ISSUE THREAD

**Issue by ruben--** [erkie/erkie.github.com#22]
I would say, personally, this is a game changer. 
Letting asteroids roam a website is a really good idea and I'm surprised it hasn't caught on like it should. Maybe there's a marketing issue here? I would suggest SEM, like AdWords, to spread the word.
Again, like it a lot.

**Comment by erkie** [comment]
@ruben-- are you still able to replicate this issue?

**Comment by ruben--** [comment]
@erkie Thanks for reaching out. A lot has happened since our last talk. Here at SpaceTech Ltd, we're still running the code and it works not only in our "peeplkillindrones" but also in partner software, such as all the SpaceX rockets. The bug is still there tho. Plz fix. 🙏

**Comment by erkie** [comment]
Hi thanks for the confirmation. Unfortunately I can't reproduce it.
